vm: true
runtime: custom
threadsafe: true
api_version: 1
service: default

manual_scaling:
  instances: 2

# At some point, we must swap vm_settings for resources
# And change runtime form 'vm' to 'custom'
vm_settings:
  machine_type: n1-standard-1
#resources:
#  memory_gb: 0.6
##  cpu: 1.0
##  memory_gb: 1.3


#  has_docker_image: 'True'

#automatic_scaling:
#  max_idle_instances: 1
#  max_pending_latency: 500ms

#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 5
#  cool_down_period_sec: 60
#  cpu_utilization:
#    target_utilization: 0.5

inbound_services:
- warmup

default_expiration: 10d
handlers:
- url: /_pipeline(/.*)?
  script: pipeline.handlers._APP
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.application
  login: admin
- url: /_ah/stats.*
  script: google.appengine.ext.appstats.ui.app
- url: /_ah/remote_api(/.*)?
  script: google.appengine.ext.remote_api.handler.application
- url: /dancedeets.png
  static_files: dancedeets.png
  upload: dancedeets.png
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /vcss/.*
  static_dir: css
- url: /vjs/.*
  static_dir: js
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /dist.*/fonts
  static_dir: dist/fonts
- url: /dist.*/img
  static_dir: dist/img
- url: /dist.*/js
  static_dir: dist/js
- url: /dist.*/css
  static_dir: dist/css
- url: /images
  static_dir: images
- url: /tools/.*
  script: main.application
  login: admin
- url: /graphql.*
  script: graphql_server.app
- url: /graphiql.*
  script: graphql_server.app
- url: /static/graphql.*
  script: graphql_server.app
- url: /admin.*
  script: admin.app
  login: admin
- url: /events/admin.*
  script: main.application
  login: admin
- url: /tasks/.*
  script: main.application
  login: admin
- url: /_ereporter
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin
- url: /mapreduce/worker_callback.*
  script: main.application
  login: admin
- url: /mapreduce/pipeline/images
  static_dir: mapreduce/lib/pipeline/ui/images
- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin
- url: /_ah/warmup
  script: main.application
  login: admin
- url: /oauth2callback
  script: oauth2client.appengine.application
- url: /oauth_setup
  script: servlets.oauth.application
- url: .*
  script: main.application

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.db
- ^(.*/)?.*\.csv
- ^(.*/)?test_data(/.*)?
- ^local_data(/.*)?
- ^local_data2(/.*)?
- ^local_data3(/.*)?
- ^assets(/.*)?
- ^download(/.*)?
- ^node_modules(/.*)?
- ^snapshotted(/.*)?
- ^scratch(/.*)?
- ^grammar-processed.*
- ^full-logs.txt
- ^r/(.*)
- ^s/(.*)
- ^snapshotted(/.*)?
- ^tmp(/.*)?
- ^build(/.*)?
#- ^(.*/)?app\.yaml
#- ^(.*/)?app\.yml
#- ^(.*/)?index\.yaml
#- ^(.*/)?index\.yml
#- ^(.*/)?.*\.spt
