application: dancedeets-hrd
vm: true
runtime: vm
threadsafe: true
api_version: 1
module: default

manual_scaling:
  instances: 2

vm_settings:
  machine_type: g1-small
  vm_runtime: python27

#  has_docker_image: 'True'

#automatic_scaling:
#  max_idle_instances: 1
#  max_pending_latency: 500ms

#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 5
#  cool_down_period_sec: 60
#  cpu_utilization:
#    target_utilization: 0.5


#resources:
#  cpu: .5
#  memory_gb: 1.3

inbound_services:
- warmup

builtins:
- remote_api: on
- appstats: on
- deferred: on

handlers:
- url: /dancedeets.png
  static_files: dancedeets.png
  upload: dancedeets.png
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
# bootstrap hardcodes the fonts path as ../fonts, which in /vcss/1234567890/bootstrap.css, comes to /vcss/fonts/xyz.font
- url: /vcss/fonts
  static_dir: css/fonts
- url: /vcss/.*
  static_dir: css
- url: /vjs/.*
  static_dir: js
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /tools/.*
  script: main.application
  login: admin
- url: /admin/.*
  script: main.application
  login: admin
- url: /events/admin.*
  script: main.application
  login: admin
- url: /tasks/.*
  script: main.application
  login: admin
- url: /_ereporter
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin
- url: /mapreduce/worker_callback.*
  script: main.application
  login: admin
- url: /mapreduce/pipeline/images
  static_dir: mapreduce/lib/pipeline/ui/images
- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin
- url: /_ah/warmup
  script: main.application
  login: admin
- url: /oauth2callback
  script: oauth2client.appengine.application
- url: /oauth_setup
  script: servlets.oauth.application
- url: .*
  script: main.application

admin_console:
 pages:
 - name: Appstats
   url: /_ah/stats

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.db
- ^(.*/)?.*\.csv
- ^(.*/)?test_data(/.*)?
- ^local_data(/.*)?
- ^local_data2(/.*)?
- ^download(/.*)?
#- ^(.*/)?app\.yaml
#- ^(.*/)?app\.yml
#- ^(.*/)?index\.yaml
#- ^(.*/)?index\.yml
#- ^(.*/)?.*\.spt
