application: dancedeets
version: v0-1-prerelease
runtime: python
api_version: 1

handlers:
- url: /boo.html
  static_files: boo.html
  upload: boo.html
- url: /dancedeets.png
  static_files: dancedeets.png
  upload: dancedeets.png
- url: /css
  static_dir: css
- url: .*
  script: main.py
- url: /tasks/.*
  script: main.py
  login: admin

