application: dancedeets
version: v0-2-eventgeohashes
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- remote_api: on
- appstats: on

handlers:
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
- url: /dancedeets.png
  static_files: dancedeets.png
  upload: dancedeets.png
- url: /css
  static_dir: css
- url: /fonts
  static_dir: fonts
- url: /images
  static_dir: images
- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin
- url: /tools/.*
  script: main.py
  login: admin
- url: /admin/.*
  script: main.py
  login: admin
- url: /events/admin.*
  script: main.py
  login: admin
- url: /tasks/.*
  script: main.py
  login: admin
- url: .*
  script: main.py

admin_console:
 pages:
 - name: Appstats
   url: /_ah/stats

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.db
- ^(.*/)?.*\.spt
