application: dancedeets-hrd
version: v1-7-location-bounds
runtime: python
threadsafe: false #sigh, appengine starts charging me more, telling me i can use threadsafe to save on instances, but then leaves admin, mapreduce, and ereporter stuck using the old cgi interfaces so i can't actually use threadsafe.
api_version: 1

inbound_services:
- warmup

builtins:
- datastore_admin: on
- remote_api: on
- appstats: on
- deferred: on

handlers:
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
- url: /dancedeets.png
  static_files: dancedeets.png
  upload: dancedeets.png
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /tools/.*
  script: main.py
  login: admin
- url: /admin/.*
  script: main.py
  login: admin
- url: /events/admin.*
  script: main.py
  login: admin
- url: /tasks/.*
  script: main.py
  login: admin
- url: /_ereporter
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin
- url: /mapreduce/worker_callback
  script: main.py
  login: admin
- url: /mapreduce/pipeline/images
  static_dir: mapreduce/lib/pipeline/ui/images
- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin
- url: /_ah/warmup
  script: main.py
  login: admin
- url: /oauth2callback
  script: oauth2client/appengine.py
- url: /oauth_setup
  script: servlets/oauth.py
- url: .*
  script: main.py


admin_console:
 pages:
 - name: Appstats
   url: /_ah/stats

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.db
- ^(.*/)?.*\.csv
- ^(.*/)?test_data(/.*)?
#- ^(.*/)?app\.yaml
#- ^(.*/)?app\.yml
#- ^(.*/)?index\.yaml
#- ^(.*/)?index\.yml
#- ^(.*/)?.*\.spt
