application: dancedeets
version: v0-1-prerelease
runtime: python
api_version: 1

handlers:
- url: /boo.html
  static_files: boo.html
  upload: boo.html
- url: /dancedeets.png
  static_files: dancedeets.png
  upload: dancedeets.png
- url: /css
  static_dir: css
- url: /admin/.*
  script: main.py
  login: admin
- url: /tasks/.*
  script: main.py
  login: admin
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  login: admin
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: .*
  script: main.py

admin_console:
 pages:
 - name: Appstats
   url: /stats
